# .rubyci/config.yml 

version: 1

build_packs:
  rails: {}
  node_js:
    # Available versions: [12..17]
    version: 12
  postgresql:
    # Available versions: [9..14]
    version: 12
  redis:
    # Available versions: [5.0, 6.0, 6.2]
    version: 6.2
  image_magick:
    # Available versions: [7.0.10-58]
    version: 7.0.10-58
  chrome:
    # Available versions: [latest]
    version: 99
  geckodriver:
    # Available versions: [latest]
    version: 0.29.1
    